# print('ASSALOMU ALEYKUM')
# print("AVTO SALONIMIZGA XUSH KEIBSIZ")
# print("QUYIDAGI SO'ROV NOMANI TO'LDIRING")
# ism = input("ISMIMINGIZNI KIRITING")
# familya = input("FAMILIYANGIZNI KIRITING")
# manzil = input("YASHASH MANZILINGIZNI KIRITING")
# telefon = input("TELEFON NOMERINGIZNI KIRITING")
# print(ism + " Ismingiz/n" + familya + "Familya/n" + manzil + "Manzil/n" + telefon + "Telefon/n" )
# print ("Qaysi mashina markasini tanlaysiz?")
# print("1 - AUDI")
# print("2 - BUGATTI")
# print("3 - OPEL")
# a1 = int(input("QAYSI MASHINA MARKASINI TANLADINGIZ"))
# if a1 == 1:
#     print('SIZ AUDI MARKASIDAGI MASHINANI TANLADINGIZ')
#     print("SIZ AUDI MARKASIDAGI QAYSI MASHINA TURLARINI TANLAYSIZ?")
#     print("1 - 'TTS ROASSTER' QIZIL RANGLI")
#     print("2 - 'TTS UPESI' SARIQ RANGLI")
#     print("3 - 'Q7' YASHIL RANGLI")
#     print("4 - 'SQ8' OQ RANGLI")
#     b = int(input("MASHINA TURINI TANLANG"))
#     if b == 1:
#         print("1- SIZ 'TTS ROASSTER' QIZIL RANGLI 55.000$ MIQDORDAGI MASHINANI TANLADINGIZ")
#     elif b == 2:
#         print("2 - SIZ 'TTS KUPESI' SARIQ RANGLI 65.000$ MIQDORDAGI MASHINANI TANLADINGIZ")
#     elif b == 3:
#         print("3 - SIZ 'SQ8' YASHIL RANGLI 95.000$ MIQDORDAGI MASHINANI TANLADINGIZ")
#     elif b == 4:
#         print("4 - SIZ 'Q7 OQ' RANGLI 75.000$ MIQDORDAGI MASHINANI TANLADINGIZ")
# print("HURMATLI MIJOZ SIZ BIZNING AVTO SALONIMIZDAN MASHINA XARID QILGANINGIZ UCHUN JAMOAMIZ BILAN SIZGA MINNADORCHILIK BILDIRAMIZ")
# a2 = int(input("QAYSI MASHINA MARKASINI TANLADINGIZ"))
# if a2 == 2:
#         print('SIZ BUGATTI MARKASIDAGI MASHINANI TANLADINGIZ')
#         print("SIZ BUGATTI MARKASIDAGI QAYSI MASHINA TURLARINI TANLAYSIZ")
#         print("1 - 'LA VOITURE NOIRE' QORA RANGLI")
#         print("2 - 'GIPERKAR' QIZIL RANGLI ")
#         print("3 - 'TUPE 57 SC' SARIQ RANGLI ")
#         print("4 - 'CHIRON SUPER SPORT' OQ RANGLI ")
# b = int(input("MASHINA TURINI TANLANG"))
# if b == 1:
#     print("1 - SIZ 'LA VOITURE NOIRE' QORA RANGLI 13 MLN YEVRO MIQDORIDAGI MASHINANI TANLADINGIZ")
# elif b == 2:
#     print("2 - SIZ  'GIPERKAR QIZIL RANGLI 11 MLN YEVRO MIQDORDAGI MASHINANI TANLADINGIZ")
# elif b == 3:
#     print("3 - SIZ 'TUPE 57 SC' SARIQ RANGLI 10 MLN YEVRO MIQDORDAGI MASHINANI TANLADINGIZ")
# elif b == 4:
#     print("4 - SIZ 'CHIRON SUPER SPORT' OQ RANGLI 21 MLN YEVRO MIQDORDAGI MASHINANI TANLADINGIZ")
# a3 = int(input("QAYSI MASHINA MARKASINI TANLADINGIZ"))
# if a3 == 3:
#     print('SIZ OPEL MARKASIDAGI MASHINASINI TANLADINGIZ')
#     print("SIZ OPEL MARKASIDAGI QAYSI MASHINA TURINI TANLAYSIZ?")
#     print("1 - 'INSIGMA GRAND' YASHIL RANGLI")
#     print("2 - 'INSIGNIA TOURER' OQ RANGLI")
#     print("3 - 'ASTRA TOURER' QIZIL RANGLI")
#     print("4 - 'CORSA - E - F' QORA RANGLI")
# b = int(input("MASHINA TURINI TANLANG"))
# if b == 1:
#     print("1 - SIZ 'INSIGMA GRAND' YASHIL RANGLI 2,6 MLN $ MIQDORDAGI MASHINANI TANLADINGIZ")
# elif b == 2:
#     print("2 - SIZ 'INSIGNIA TOURER' OQ RANGLI 4,3 MLN $ MIQDORDAGI MASHINANI TANLADINGIZ")
# elif b == 3:
#     print("3 - SIZ 'ASTRA TOURER' QIZIL RANGLI 3 MLN $ MIQDORDAGI MASHINANI TANLADINGIZ")
# elif b == 4:
#     print("4 - SIZ 'CORSA -E - F' QORA RANGLI 3.7 MLN $ MIQDORDAGI MASHINANI TANLADINGIZ")

# else:
#     print("HURMATLI MIJOZ BIZNING AVTOSALONDAN MASHINA XARID QILGANINGIZ UCHUN SIZGA MINNADORCHILIK BILDIRAMIZ")

