# for x in range(10):
    # for y in range(10):
        # shart1 = y == 11 or y==18
        # if x == 3: 
            # print("* ", end='')
        # else:
            # print(" ", end='')
    # print()

# 
# size = 6
# for i in range(size):
    # for j in range(size):
        # if i == 0 or j == 0 or i == size -1 or j == size -1 or i == j or size -1 - i == j:
            # print("* ", end='')
        # else:
            # print("oooo__--__oooo", end=" ")
    # print()

# 
# print('1  - misol ')

# a = int(input('son1 kiriting -'))
# b = int(input('son2 kiriting -'))
# c = int(input('son3 kiriting -'))

# m=max(a,b,c)
# print(m)


# print('2  - misol ')
# son1 = ""
# son2 = " "
# q = " "
# a = input('misol kiriting -')
# for i in a:
#     if i.isdigit() :
#         son1 += i
#     if i.isspace():
#         son2 = " "
#     if i.isdigit():
#         son2 += i
# s1 = len(son1) 
# s2 = len(son2) 
# son_1 = (int(son1) - int(son2)) // (10**s2)
# p='/'
# l='*'
# m='-'
# n='+'
# if m in a:
#     q = int(son_1) - int(son2)
# elif p in a:
#     q = int(son_1) / int(son2)
# elif l in a:
#     q = int(son_1) * int(son2)
# elif n in a:
#     q = int(son_1) + int(son2)
# print(q)

# print('3 - misol ')

# a = (input('true - false ==> '))
# a = str(a)
# b = "true"
# c = "false"
# if b in a:
#     print("true")

# elif c in a:
#     print(str("false"))
